DROP TABLE IF EXISTS items;

CREATE TABLE items (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    datum DATE NOT NULL,
    description TEXT NOT NULL,
    amount DECIMAL(6,2) NOT NULL
);
